// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Ectry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Ectry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEntryWithAccountID(ctx context.Context, arg ListEntryWithAccountIDParams) ([]Ectry, error)
	ListEntryWithID(ctx context.Context, arg ListEntryWithIDParams) ([]Ectry, error)
	ListTransferWithFromAccountID(ctx context.Context, arg ListTransferWithFromAccountIDParams) ([]Transfer, error)
	ListTransferWithID(ctx context.Context, arg ListTransferWithIDParams) ([]Transfer, error)
	ListTransferWithToAccountID(ctx context.Context, arg ListTransferWithToAccountIDParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Ectry, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
