name: ci-test

on:
  # 向 master 分支推送时触发
  push:
    branches: [ "master" ]
  # 合并到 master 分支的拉取请求触发
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        # 安装 Go
        uses: actions/setup-go@v4
        # 参数
        with:
          go-version: '1.19'
        id: go

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          ls -l
          sudo mv migrate /usr/bin/
          which migrate



      - name: Make migrate postgres
        # run: make migrateup
        run: migrate -path db/migration -database "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable" -verbose up


      - name: Test
        # run: make test
        run: go test -v -cover ./...
